INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Psychological Association','AmPsychAss',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Association for Cancer Research','AmAssCaRe',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Association for Computing Machinery','AssCompMach',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Springer','SpringerAdis',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Institute of Aeronautics and Astronautics','AmIntAerAstro',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Allen Press','AllenPres',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Chemical Society','AmCheSoc',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Economic Association','AmEcoAss',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Institute of Physics','AmInsPhy',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Medical Association','AmMedAsso',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Physical Society','AmPhySoc',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Physiological Society','AmPhysgSoc',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Society for Microbiology','AmSocMic',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Thoracic Society','AmThoSoc',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American College of Physicians','AmCollPhy',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Annual Reviews','AnnuRev',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Society for Biochemistry and Molecular Biology','AMoleBio',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Society for Pharmacology and Experimental Therapeutics','AmSocPhaExThe',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Bentham Science','BenthSci',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('BioOne','BioOne',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Brill','Brill',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('British Institute of Radiology','BriInstRad',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('British Medical Journal','BriMedJ',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Cambridge University Press','CamUniPre',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Canadian Medical Association','CanMedAss',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Canadian Science Publishing','CanSciPub',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Elsevier','CellPressELS',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Elsevier','ClinicasELS',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Cold Spring Harbor Laboratory Press','ColSprHaLabPre',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('The Company of Biologists','CompBiolg',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Commonwealth Scientific and Industrial Research Organisation','CoSciIndReseOrg',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Elsevier','DoymaELS',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Duke University Press','DukUniPres',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Edinburgh University Press','EdiUniPres',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Electrochemical Society','ElechSoc',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Emerald','Emerald',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Federation of American Societies for Experimental Biology','FedAmSocExpBio',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Elsevier','FreedomELS',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Genetics Society of America','GenSocAm',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Geological Society of America','GeoSocAm',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Geological Society of London','GeoSocLon',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Guilford Publications','GuilfPub',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Taylor & Francis','TaylorMed',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Ingenta','Ingenta',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Institute of Physics','InstofPhys',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Association of Neurological Surgeons','AmAssNeuSurg',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Academy of Periodontology','AmAcaPer',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Journal of Visualized Experiments','Jove',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('S. Karger AG','Karger',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Kluwer Law International','KluwLawInt',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Mary Ann Liebert','MarAnnLie',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Society for Cell Bioloy','AmSocCelBio',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Massachusetts Institute of Technology Press','MitPres',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Mycotaxon','Mycotaxon',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Springer Nature','SprinNat',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Massachusetts Medical Society','MassMeSoc',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Optical Society of America','OptSocAm',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Lippincott Williams & Wilkins','LippWillW',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Oxford University Press','OxfUniPre',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Palgrave Macmillan','PalgMac',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Parenteral Drug Association','ParDrugAss',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('National Academy of Sciences','NatAcaSci',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Project Euclid','ProjectEuc',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Project Muse','ProjectMus',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('The Rockefeller University Press','RockUniPre',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Royal Society of Chemistry','RoySocChem',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Royal Society Publishing','RoySocPub',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Sage Publications','SagePub',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Association for the Advancement of Science','AmAssAdvSci',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Seismological Society of America','SeismSocAm',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Elsevier','SeminarsELS',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Society for Industrial and Applied Mathematics','SocIndAppMath',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('The Microbiology Society','MicrobSoc',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Society for Neuroscience','SocfNeursc',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Springer','SpringerJou',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Taylor & Francis','Tay&Fran',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Society of Tropical Medicine and Hygiene','AmSocTropMedHyg',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Association of Immunologists','AmAssImm',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Thieme Medical Publishers','Thieme',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('University of California Press','UniCalfPres',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('University of Chicago Press','UniChicaPres',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('University of Wisconsin Press','UniWiscPres',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Walter de Gruyter','WaltdGruyt',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Wiley-Blackwell Publishing','Wiley',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Wiley-Blackwell Publishing','WileyBackF',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Bibliomedia','Bibliomedia',2,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('ClinicalKey','ClinicalKey',2,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('CAB Reviews Full Text','CAB',2,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Ebsco','Ebsco',2,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Enferteca','Enferteca',2,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Gale','Gale',2,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('IEEE Xplore digital library','IEEE',2,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('JSTOR','JSTOR',2,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('MathSciNet','MathSciNet',2,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Micromedex','Micromedex',2,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Journals@Ovid','JourOvid',2,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Proquest','Proquest',2,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('SciFinder (antes Chemical abstracts)','SciFinder',2,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('SPIE Digital Library','SpieDL',2,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Chemical Society','AmCheSoc',3,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Institute of Aeronautics and Astronautics','AmIntAerAstro',3,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Allen Press','AllenPres',3,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Psychological Association','AmPsychAss',3,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('BioOne','BioOne',3,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Duke University Press','DukUniPres',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('CAB Reviews Full Text','CABRevFullTex',3,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Cambridge University Press','CamUniPre',3,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('ClinicalKey','ClinicalKey',3,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Elsevier','Elsevier',3,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Ebsco','Ebsco',3,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Eighteenth Century Collections Online','ECCO',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Early English Books Online','EEBO',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Encyclopaedia Britannica','EncpBritan',3,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('IEEE Xplore digital library','IEEE',3,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('JSTOR','JSTOR',3,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Making of the Modern World','MOMW',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Society for Industrial and Applied Mathematics','SIAM',3,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('SPIE Digital Library','SpieDL',3,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Springer','Springer',3,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Springer Protocols','SpringerProtoc',3,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Teatro español del siglo de oro','TESO',3,4);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Walter de Gruyter','WaltdGruyt',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Wiley','Wiley',3,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Wiley Protocols','WileyProtoc',3,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('ITMS Group','ACSESS DL',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Association on Intellectual and Developmental Disabilities','AmAssInDeDis',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Allen Press','AnestProg',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Ecological Society of American','EcoSocAm',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Taylor & Francis','Maney',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Cengage','NatGeo',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Cengage','NatGeoPeo',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('World Scientific Publishing','WorldScif',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Benezit Dictionary of Artists','BenezDicArt',2,4);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Grove Music Online','GroveMus',2,4);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Alliance of Crop, Soil, and Environmental Science Societies','ACSESS DL',3,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Thoracic Society','AmThoSoc',3,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Brill','Brill',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Gale Virtual Reference Library','GaleVirtRefLib',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('LGBTQ History and Culture Since 1940','LGBTQI',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('LGBTQ History and Culture Since 1940 II','LGBTQII',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Mapping the World: Maps and Travel Literature','NCCOMapping',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Women Transnational Networks','NCCOWomen',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Photography: The World through the Lens','NCCOPhotog',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Women''s Issues and Identities','NCCOWomen''s',3,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Geological Society of America','GeoSocAm',3,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Project Euclid','ProjectEuc',3,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Thieme Medical Publishers','Thieme',3,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('World Scientific Publishing','WorldScif',3,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('American Society for Nutrition','AmSocNut',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Edinburgh University Press','EdiUniPres',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('The Royal Society Publishing','RoySocPub',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Seismological Society of America','SeismSocAm',1,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Wiley-Blackwell Publishing','WileyProtoc',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('ARTStor','ARTStor',2,4);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('CAB abstracts','CAB',2,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Clarivate Analytics','ClarivaAnalyt',2,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Ei Village','EiVillaELS',2,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('OCLC','OCLC',2,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Ovid Bases','OvidBases',2,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Reaxys','ReaxysELS',2,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('SciFinder (antes Chemical abstracts)','SciFinder',2,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Scopus','Scopus',2,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Springer Materials','SpringerMater',2,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('UptoDate','UptoDate',2,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Walter de Gruyter','WaltdGruyt',2,4);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Zentralblatt MATH database','ZentralMath',2,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Elsevier','Elsevier',1,5);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Massachusetts Medical Society','MassMeSoc',1,3);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('World Scientific Publishing','WorldScif',1,2);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Alliance of Crop, Soil, and Environmental Science Societies','ACSESS DL',2,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Geobase','Geobase',2,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('GeoRef','GeoRef',2,1);
INSERT INTO fuente_informacion(nombre_fuente,acronimo,id_recurso,id_area) values('Compendex','Compendex',2,1);