INSERT INTO tc_ITMS_servicios(nombre_servicio) values('UpToDate');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Clinical Key');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebsco Host');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('PubMed');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Science Direct');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Scopus');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ed Med Panam');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('JSTOR');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ieee Xplore');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Wiley Online Lib');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Springer Link');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Micromedex');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Nature Publishing');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Web of Science');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Am Chem Soc');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Vlex');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Geobase-GeoRefS');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Journals@Ovid');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Digitalia Hispánica');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Bib Pearson');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Reaxys');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Taylor & Francis');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Bibliotechnia');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Enferteca');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Chem Abstracts');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('SciFinder');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Dynamed');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('New Eng Jour Med');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Acad Sear Comp');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Bib Digital Cengage');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('BMJ Journals');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Royal Soc Chem');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Sage Journals');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('E-Libro');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Bibliomedia');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('PsycINFO');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Hachette Livre');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Diss Global');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proquest');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('SPIE Dig Lib');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Cambridge Core');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebook Central');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('iPublish Central');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Oxford Jour');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('ACM');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('In4mex');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Incites JCR');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Encyc Britannica');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Bib Digital Ilce');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Emerald Insight');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('DawsonEra');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs CINAHL FT');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('BioOne');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('ASCE Library');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Myilibrary');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Aps Journals');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('SciELO México');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Thieme Connect');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('APA PsycNET');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('AIP Proceedings');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('The Opt Soc Pub');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Medline OVID');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Oxford Scholar');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('JSTOR Glob Plants');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('ARTstor');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Karger Publishers');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Scientific.Net');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Biol Abs');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Enfer Día');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('ERIC');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Dent Oral');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Mathscinet');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('ACSESS');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq MEDLINE');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Annual Reviews');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs eJournals');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Sage Pub');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Hapi Online');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Cochrane');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Taylor Francis Ebooks');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('AGRICOLA');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Safari Books');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Curr Cont');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Econolit FT');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('OCÉANO Saber');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Economática-FINSAT');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Dykinson Lib');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Eight Cent Coll');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('PsycArticles');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Institute of Physics');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('WOS Book Cit');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Aluminium');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Magnolia Press');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('SciELO Brazil');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Annals Inter Med');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ingenta Connect');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Arch Open Library');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Anim Healt');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Anim Science');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('MedScape');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Oecd Ilibrary');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('AGRIS');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('EBM Cochrane Trials');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Derwent Inn Inx');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jaypee Bros Med Pub');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Biol Sc');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('JoVE Sc Edu');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Springer Mater');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('The Uni Chicago Jour');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Springer Books');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('McGraw Hill SSO');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('World Sci Pub');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Acland Anatomy');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ulrichs Perio Dir');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq AIDS');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq LLBA');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jour Periodont Online');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('OCLC Articles First');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq LISA');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Bus Source Comp');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Fuent Acad');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Benezit Dict');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Early Eng Books');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('EBM Cochrane Rev');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Anatomy Tv');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Incites ESI');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('OCLC WorldCat');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Dict Nat Prod');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('EBM ACP Jour');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('PBOO MDConsult');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Vitalsource BC');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Brit Acad');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Els Citable Revs');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Springer Prot');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Science - AAAS');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Rev Inv Ciencia');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Encyc App Ling');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Fac Med UNAM');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('The Ency App Ling');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Medic Lat');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Bacterio');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Routl Enc Philos');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('The Arabidopsis Info');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Chicago Manual');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Philpapers');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('PNAS');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('CAB Reviews');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Wolters Klu Jour');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Comm Mass Med');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Algology');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('SIAM');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Wiley Proto');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Environ Comp');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Scitation');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('JAMAevidence');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('CSIRO Pub');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Ind Microb');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('MIT Press Journals');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Art Arch Src');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs MLA Int Bibl');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('NRC Research Press');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Aqua Comp');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Bib Digital Género');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Hisp Am Newsp');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Am Physiological Soc');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('JAMA Network');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('CLASE');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Zoolog record');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Lib Info Sour');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Water Intelligence Online');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Science Synth');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Deupress');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Am Hist Life');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('SciELO Chile');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Oxford Handbook');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq ASFA');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('SourceOECD');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('FILOS');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('CAB Abstracts');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Latindex');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Am Thoracic Soc');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Acta Sanctorum');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Biocyc DB');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('SciELO Argentina');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Pearsonbv');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Am Meteoro Soc');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Project Muse');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jour Neurosurgery');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Philos Inx');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Human');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Comp Info Abs');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('World LA Newsp');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Eb20');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('INFOBILA');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Gend Watch');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Alfaomega');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Manual Moderno');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Am Acad Pediatrics');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('L\'Annee Philologique');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Periódica');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Natur Prod Upd');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Visión Méd Virt');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs MLA Dir Per');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Uni Cal Press');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('The Am Soc Mech Eng');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Environ Scs');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Zentralblatt MATH');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Des Fungi Bact');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Teatro Español');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs FSTA');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Fed Am Soc Exp Biol');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Loeb Classics');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Mat Bus');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Biochemical Soc');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Fam Soc Stud');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Mak Mod World');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Conf Inx');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Gender Studies');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Newsp Sour');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq TOXLINE');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('IGI Global');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('IQOM');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Plant Sc');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Springer Nat Exp');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Eng Mat Abs');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jour Biol Chem');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Copp Data');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Cell Press');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Biomed Central');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Women Trans');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Am Jour of Botany');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Hist Abs Ft');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('EMBASE');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Forest Science');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('MAPAMEX');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Wat Res Abs');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Bib Teubner Lat');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('EUTERPE');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('INSPEC');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Am Soc Clin Oncol');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Cold Spr Harbor Pers Biol');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jour Cell Biol');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jour Pharma Exp Thera');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Ceram Abs');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('ASP Conf');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Project Euclid');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('CRCnetBase');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('ETDEWEB');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Internet Sci Pub');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Keesing\'s World');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('POPLINE');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('PACIOLLI');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs World Tex');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('MDConsult');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('UNAMJURE');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('University Press');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Newsbank-Readex');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Per Elect Psic');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Elec Comm');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Brill\'s New Pauly');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Mec Eng');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Crop Prot');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Elsevier Journals');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Euro Journal Vasc Surg');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Human Rel');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jour Clin Ped Dent');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Molec Pharma');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Uni Vera');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Am Soc Nephrology');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs RILM Abs');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Geol Soc Ame');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Access Eng');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('IOS Press');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Rad Soc North Am');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Universalis');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('WilsonWeb');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Cambridge');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Reg Bus News');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Encyc Life Sc');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('J-Gate Plus');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq METADEX');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Safety Risk');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Rev PUCP');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Catalys React');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Dist Map Plant Dis');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('GeoScienceWorld');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('ICE Virtual Library');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Stat Abs USA');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ebs Left Inx');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('GEOMEX');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Indian Journals');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Torrossa Casalini');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Brepols Online');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Byzan Biblio');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Forest Comp');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Liebert');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Ocea Abs');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('The Am Soc Cell Biol');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Who World Org');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Can Med Assoc Jour');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Elgaronline');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jour Cell Scien');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jour Exp Med');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jour Oper Dent');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('The Nat Acad Sci');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Acad Onefile-Info Acad');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Am Assoc Clin  Chem');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Anesthesia Progress');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Bioscientifica');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Cahiers Biol Mar');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('INEGI');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('The Indian Vet Jour');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('WOS FSTA');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Akadémiai Kiadó Jour');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Brill\'s New Jacoby');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Brit Inst Radiol');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Com Eco Am Lat Caribe');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Corrosion Journal');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('New York Times');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Oxford Reference');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Proq Solid State');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Aenormas');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Am Assoc Cancer Res');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Dist Map Plant Pes');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Ed Sintesis');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jour Ortho Spor Phys Ther');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Música Mexicana');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Nat Geo Virt Lib');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Peter Lang');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Rev Per Uni Nal Plata');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('The SAO-NASA Astro Data');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Cairn');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Chem Hazards Ind');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('CliniCAPS');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Critical Care Clinics');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Dekker');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Emerald Gro Pub');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('FAO');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Guilford Pub');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Int Labour Org');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Inter-Res Sci Cen');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jour Vet Med Edu');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Microbiology Soc');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Oxford Bibliog');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('The Chem Soc Japan');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('The IORMC');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Vet Clinics');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Wagenin Acad Pub');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Anthropology Now');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('ASTM Compass');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Begell House');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Byzantion Nea Hellás');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Casalinilibri');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Deuts Nat Bibl');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('East Art Map');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Eduke Books Coll');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('ENGnetBASE');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Found Direct Online');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Harvard Ed Pub');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Informit Search');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Int Jour Limnology');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Intl Prog Chem Saf');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Jour Dynam Syst');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Kluwer Law');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Knovel');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Micropaleo Press');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Mineral Soc Am');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('MIT Cognet');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Nanzan Inst Rel Cul');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('NMC Jour');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('OCLC PURL Service');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Oxford Res Ency');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Palgrave Connect');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Per Elet CNEC');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('RCN Publishing');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Rev Bras Gestão Des Reg');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Rockefeller Uni Press');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('The Jour Lipid Res');
INSERT INTO tc_ITMS_servicios(nombre_servicio) values('Thes Linguae Graecae');