update tc_guia_recursos set descripcion='Academic Search Ultimate contiene miles de títulos de publicaciones periódicas en texto completo, y publicaciones arbitradas, de múltiples disciplinas académicas, Además, ofrece índices y resúmenes de más de 11,600 publicaciones especializadas y un total de más de 12,200 publicaciones diversas, entre las que se incluyen monografías, informes y conferencias. Esta colección académica ofrece una cobertura de información en textos completos sobre muchas áreas de estudio académico, incluyendo, entre otras: ciencia animal, antropología, estudios regionales, astronomía, biología, química, ingeniería civil, ingeniería eléctrica, estudios multiculturales y étnicos, ciencia y tecnología de los alimentos, ciencia general, geografía, geología, derecho, ciencia de materiales, matemáticas, ingeniería mecánica, música, ciencias farmacéuticas, física, psicología, religión y teología, veterinaria, estudios sobre la mujer, zoología y muchos otros campos. Academic Search Complete ofrece información fundamental proveniente de numerosas fuentes exclusivas de esta gran colección. Dispone además de referencias citadas con posibilidad de búsqueda para más de 1,400 publicaciones. ' where nombre_recurso='Academic Search Ultimate';











update tc_guia_recursos set descripcion='Biological sciences es una base de datos referencial multidisciplinaria que ofrece acceso en línea a resúmenes y citas de más de 8,000 publicaciones periódicas, así como a las actas de congresos, informes técnicos, monografías y libros seleccionados y las patentes, todos ellos relacionados con las áreas de biología, biología marina, microbiología, biología molecular, micología, biomedicina, biotecnología, bacteriología, zoología y ecología, así como sobre algunos aspectos de la agricultura y la veterinaria. Su actualización es mensual con aproximadamente 13,670 nuevos registros que se agregan. La base de datos puede contener resúmenes que no aparecen en forma impresa. ' where nombre_recurso='Biological science';
update tc_guia_recursos set descripcion='BioOne s una base de datos de texto completo conformada poruna colección 183 revistas con alto impacto en el área de biociencias pertenecientes a más de 158 editores. Estos títulos son producidos por sociedades académicas y editores no comerciales y la mayoría estaban previamente disponibles solamente en forma impresa. BioOne fue desarrollada por el American Institute of Biological Sciences (AIBS), por SPARC (Scholarly Publishing and Academic Resources Coalition), la University of Kansas, la Greater Western Library Alliance y Allen Press. El objetivo de la organización no es lucrativo para la diseminación de información de las áreas biológicas, ecológicas y de ciencias del medio ambiente que aseguren la recuperación de la inversión y logren ser sustentables. Los temas cubiertos son: aracnología, escarabajos, crustáceos, ecología, botánica económica, Entomología, ciencia del medio ambiente, biología evolutiva, helechos, pesca, genética; líquenes, mamíferos, microbiología, musgos y hepáticas, historia natural, ornitología, paleontología, parasitología, fotobiología, reproducción, reptiles, ciencia veterinaria y zoología. En cuanto a la cobertura, algunas revistas son anteriores a 1998, aunque la mayoría a partir de 2000. La actualización es mensual, cubre a más de 73,930 registros hasta febrero de 2010.' where nombre_recurso='BioOne';
update tc_guia_recursos set descripcion='BMJ Best Practice es la única herramienta necesaria para respaldar las decisiones clínicas en el punto de atención. Clasificado como una de las mejores herramientas de apoyo a la decisión clínica en todo el mundo; BMJ Best Practice proporciona acceso rápido y fácil a la información más reciente basada en evidencia para profesionales de la salud. Está estructurado de forma única en torno a la consulta del paciente con consejos sobre la evaluación de los síntomas, la ordenación de las pruebas, el enfoque del tratamiento y el seguimiento. ' where nombre_recurso='BMJ Best Practice';
update tc_guia_recursos set descripcion='Book Citation Index - Science es una base de datos referencial que contiene información sobre investigación de alta calidad, proveniente de más de 50,000 libros de las principales editoriales en el área de ciencias. Los registros contienen la información de títulos, autores, palabras claves, resúmenes, referencias citas así como otros detalles. Book Citation Index – Science es una de las fuentes más consultadas por los investigadores para actualizar la información científica de calidad y actualidad. Se tiene acceso en línea desde 2005 a la fecha. Su actualización es semanal.' where nombre_recurso='Book Citation Index - Science';


update tc_guia_recursos set descripcion='Cambridge Core publica una amplia gama de contenidos académicos de Cambridge University Press. Actualmente publica más de 380 revistas académicas abarcando temas como humanidades, ciencias sociales, ciencias, tecnología y medicina. De igual manera esté recurso edita más de 33,000 libros electrónicos abarcando temas de astronomía, estudios de Shakespeare, economía, matemáticas y política.' where nombre_recurso='Cambridge Core';

update tc_guia_recursos set descripcion='Clinical Key es una herramienta de información Basada en Evidencia Médica, es un motor de búsqueda clínico diseñado para satisfacer las necesidades específicas de los médicos. Contiene más de 660 revistas científicas, 1100 libros de referencia, 1400 Fichas de medicamentos para España, 2900 monografías de medicamentos, 5000 guías de actuación clínica, 15000 folletos personalizables para pacientes y más de 17000 Vídeos de procedimientos médicos. ' where nombre_recurso='Clinical Key';




update tc_guia_recursos set descripcion='CCC: Agriculture, biology & environmental sciences contiene referencias bibliográficas y resúmenes de publicaciones especializadas en agricultura, biología y ciencias ambientales, que remiten a la fuente de publicación del texto. La actualización de la base de datos es semanal e incluye más de 1,040 títulos de revistas.' where nombre_recurso='Current contents connect: agriculture, biology & environmental sciences';
update tc_guia_recursos set descripcion='CCC: Clinical medicine Contiene referencias bibliográficas, tablas de contenido y resúmenes de artículos, editoriales, de reuniones, comentarios de revistas y libro, especializadas en medicina clínica y de ediciones recientemente publicadas. Estas publicaciones se clasifican en disciplinas tales como: anestesia, cuidados intensivos, medicina cardiovascular, sistema respiratorio y cirugía. Incluye más de 1,120 revistas y libros seleccionados por su relevancia a la investigación en medicina clínica. ' where nombre_recurso='Current contents connect: Clinical medicine';
update tc_guia_recursos set descripcion='CCC: Life sciences contiene referencias bibliográficas, tablas de contenido y resúmenes de artículos de revistas, capítulos, libros y actas de congresos, referentes a las ciencias de la vida. Estas publicaciones se encuentran clasificadas dentro de disciplinas tales como: zoología, botánica, célula, biología para el desarrollo y fisiología y ciencias animal y vegetal. Incluye más de 1,370 revistas y libros seleccionados por su relevancia a la investigación en ciencias de la vida.' where nombre_recurso='Current contents connect: Life sciences';
update tc_guia_recursos set descripcion='CCC: Social & behavioral sciences contiene referencias bibliográficas, tablas de contenido completas y resúmenes de artículos de revistas, capítulos, libros y actas de congreso, referentes a las ciencias sociales y del comportamiento. Estas publicaciones se clasifican en disciplinas tales como: economía; psicología; salud pública y ciencias de la salud. Incluye más de 1,620 revistas y libros seleccionados por su relevancia a la investigación en las ciencias sociales.' where nombre_recurso='Current contents connect: Social & behavioral sciences';
update tc_guia_recursos set descripcion='Dentistry & Oral Sciences Source ofrece información actualizada de más de 231 revistas en texto completo, 31 monografías, una colección de memorias de conferencias y las publicaciones internacionales líderes relacionadas a todas las especialidades en el campo de la endodoncia, patología oral y maxilofacial, radiología, cirugía, ortodoncia, periodoncia, odontología pediátrica entre otras.' where nombre_recurso='Dentistry & Oral Sciences Source';


update tc_guia_recursos set descripcion='Dictionary of Natural Products es una base de datos referencial cuya especialidad es el área de la química. Presenta estructuras y sustancias químicas. Incluye descripciones y datos numéricos en química, física, así como propiedades y compuestos biológicos; nombres de compuestos comunes y sistemáticos; referencias literarias; diagramas estructurales y conexiones asociadas a tablas. ' where nombre_recurso='Dictionary of Natural Products';
update tc_guia_recursos set descripcion='Dissertations & Theses contiene la colección mundial más completa de tesis y tesinas de diversas disciplinas. Esta base de datos se considera el archivo oficial de disertaciones digitales para la Biblioteca del Congreso y para la investigación de posgrado. Incluye 2,7 millones de citas de disertaciones y tesis de todo el mundo desde 1861 hasta la actualidad, junto con 1,2 millones de disertaciones en texto completo que están disponibles para su descarga en formato PDF. Más de 2,1 millones de títulos disponibles para la compra como copias impresas. Dissertations & theses ofrece texto completo para la mayoría de las disertaciones añadidas desde 1997 y fuerte cobertura retrospectiva en texto completo de las obras antiguas de posgrado. Cada año se agregan más de 70,000 nuevas disertaciones y tesis. ' where nombre_recurso='Dissertations & Theses';


update tc_guia_recursos set descripcion='DynaMed es una herramienta de referencia clínica elaborada por médicos, dirigida a médicos y profesionales de la atención de la salud, pensada para usarse principalmente en el punto de atención al paciente. Contiene sumarios para más de 3,000 temas organizados por especialidad clínica.' where nombre_recurso='DynaMed';



update tc_guia_recursos set descripcion='Emerald Insight es una editorial fundada en 1967. Proporciona acceso a más de 208 títulos de revistas en formato electrónico desde 1996 a la fecha. Cubre temas como contabilidad, finanzas, economía, negocios, gestión y estrategia, gestión de la información y del conocimiento, ingeniería, educación, salud, asistencia social entre otros.' where nombre_recurso='Emerald Insight';

update tc_guia_recursos set descripcion='Encyclopedia of Life Sciences es un recurso que presenta una colección de artículos científicos relacionados con las áreas de ciencias de la vida, bioquímica, bioética, biología celular, ecología, inmunología, microbiología, biología molecular, virología entre otros. ' where nombre_recurso='Encyclopedia of Life Sciences';
update tc_guia_recursos set descripcion='Enfermería al día proporciona un recurso fácil de usar para el personal de enfermería, administradores de enfermería, estudiantes de enfermería y bibliotecarios de hospital. Ofrece la mejor evidencia clínica disponible más reciente y el conocimiento sobre las condiciones y enfermedades a través de una interfaz gráfica especcializada en el área. ' where nombre_recurso='Enfermería Al Día';







update tc_guia_recursos set descripcion='FSTA: Food Science and Technology Abstracts es una base de datos referencial que contiene referencias bibliográficas y resúmenes en el rubro de la alimentación, la tecnología de alimentos y la nutrición humana. Incluye el resumen de artículos publicados en más de 1,800 revistas¸ resúmenes de tesis, libros, conferencias, patentes, y otros documentos publicados desde 1969 a la actualidad, publicada en más de 40 idiomas. Cada registro cuenta con un resumen altamente informativo, que incluyen los puntos clave, conclusiones y se asignan términos del índice. Frecuencia de actualización semanal.' where nombre_recurso='FSTA: Food Science and Technology Abstracts';
update tc_guia_recursos set descripcion='El contenido disponible en Global Plants es el resultado de un esfuerzo conocido como la Iniciativa Global Plants (GPI), cuyo compromiso es buscar cooperación internacional de los principales herbarios del mundo para digitalizar y poner ejemplares de especímenes disponibles en ellos. Actualmante participan más de 300 instituciones de más de 70 países.' where nombre_recurso='Global Plants';



update tc_guia_recursos set descripcion='Journals Ovid incluye cientos de publicaciones científicas, técnicas y médicas de más de 50 editores y sociedades. Es la segunda generación de Ovid Full Text, que combina todas las capacidades de Ovid Full Text Collections con varias características y funciones importantes.Se actualiza diariamente para garantizar el acceso a los temas publicados más recientemente.' where nombre_recurso='Journals@Ovid';
update tc_guia_recursos set descripcion='JoVE Science Education es una biblioteca innovadora de video-colecciones que enseñan conceptos claves y técnicas fundamentales. Simples y fáciles de comprender, cubren temas en biología, química, física, medicina,enfermería, ingenierías, psicología y manuales de laboratorio.' where nombre_recurso='JoVE Science Education Database';


update tc_guia_recursos set descripcion='MEDLINE es una base de datos referencial integrada por una recopilación completa de revistas sobre literatura biomédica y clínica. La base de datos se actualiza a diario, contiene más de 22 millones de registros de revistas, libros y conferencias, cubre los temas de biología, psicología, química, bioingeniería, entre otros.' where nombre_recurso='MEDLINE (Proquest)';


update tc_guia_recursos set descripcion='Micromedex provee el acceso a un vasto acervo sobre medicina clínica, se actualiza constantemente. Sus citas y referencias provienen de una gran diversidad de fuentes médicas. Con la participación en el trabajo editorial de más de 100 profesionistas médicos de diversas especialidades, y con especial énfasis en: farmacológica, fármacos para el uso de médicos, químicos y farmacéuticos, interacciones de un medicamento con otros fármacos, hierbas medicinales, alimentos, patologías, alcohol, tabaco y pruebas de laboratorio además de reacciones alérgicas previas, así como toxicología, educación para los pacientes, y enfermedades.' where nombre_recurso='Micromedex';

update tc_guia_recursos set descripcion='Natural Product Updates contiene resúmenes de los nuevos avances de productos químicos naturales; incluyendo los diagramas estructurales, nombres taxonómicos, formulas moleculares, así como propiedades físicas y biológicas activas.' where nombre_recurso='Natural Product Updates';
update tc_guia_recursos set descripcion='Newspaper Source es una base de datos referencial que proporciona acceso en línea al texto completo de más de 70 periódicos de Estados Unidos, e internacionales y contiene resúmenes e indización de los siguientes documentos: el New York Times, Wall Street Journal, The Christian Science Monitor, y Usa Today, The Washington Post, The Washington Times, The Times (Londres), The Toronto Star, etc. La cobertura total incluye más de 500,000 artículos, también contiene el texto completo selectivo de 376 diarios regionales de Estados Unidos. Adicionalmente, se incluyen las transcripciones de televisión y el texto completo de noticias de radio de la CBS News, CNN, CNN International, FOX News, NPR, etc.' where nombre_recurso='Newspaper Source';
update tc_guia_recursos set descripcion='Oceanic abstracts es una base de datos referencial y bibliográfica centrada exclusivamente en la literatura técnica mundial relacionada con el medio ambiente y de aguas salobres y marinas. Reconocida como una de las principales fuentes de información sobre temas relacionados con los océanos. La cobertura temática aborda: la biología marina y oceanografía física, pesca, acuicultura, los recursos no vivos, meteorología y geología, además de temas ambientales, tecnológicos y legislativos. Su actualización es mensual y comprende actualmente más de 420,761 registros.' where nombre_recurso='Oceanic abstracts';


update tc_guia_recursos set descripcion='PsycArticles es la base de datos que ofrece acceso al texto completo de artículos publicados en más de 100 revistas de la APA y editores afiliados. Presenta contenido histórico que data más allá de un siglo así como información actual. El recuso ésta dirigido a estudiosos de la psicología: investigadores, profesionales, estudiantes y educadores.' where nombre_recurso='PsycArticles';
update tc_guia_recursos set descripcion='PsycINFO es una base de datos referencial y bibliográfica especializada en literatura psicológica que contiene citas y resúmenes de artículos revisados por pares de revistas, así como de capítulos de libros, libros, tesis e informes técnicos, todo en el campo de la psicología y los aspectos psicológicos de las disciplinas relacionadas, como la medicina, psiquiatría, enfermería, sociología, educación, farmacología, la fisiología, la lingüística, la antropología, los negocios y derecho. PsycINFO es elaborada por la American Psychological Association (APA). Incluye material internacional, seleccionado entre más de 2,450 publicaciones periódicas de más de 49 países, escrito en 29 idiomas. Más de 80,000 registros se agregan anualmente a través de actualizaciones semanales.' where nombre_recurso='PsycINFO';
update tc_guia_recursos set descripcion='PubMed es una base de datos referencial que provee el acceso en línea a más de 6 millones de citas y resúmenes más importantes en lo que respecta a la literatura biomédica en todo el mundo. PubMed contiene una amplia variedad de temas médicos relacionados con la investigación, práctica clínica, administración, asuntos de política, y los servicios de salud. Producida por la Biblioteca Nacional de Medicina de Estados Unidos. La cobertura temática, incluye: anatomía, trastornos de la comunicación, la microbiología, las profesiones sanitarias, patología, fisiología, psiquiatría, toxicología, odontología, parasitología, biología reproductiva, epidemiología, terapia génica, la intervención quirúrgica y farmacéutica; la práctica de enfermería, aspectos éticos y legales, el funcionamiento institucional, laboratorio técnicas y procedimientos de diagnóstico relacionadas con la salud, la educación permanente; fármacos en investigación y nuevos usos de drogas, y algunos la medicina veterinaria.  ' where nombre_recurso='PubMed';

update tc_guia_recursos set descripcion='Sage Publishing incluye más de 900 revistas que cubren las humanidades, ciencias sociales y ciencia, tecnología y medicina, y más de 400 revistas son de sociedades y asociaciones académicas.' where nombre_recurso='Sage Publishing';

update tc_guia_recursos set descripcion='ScienceDirect es la plataforma de consulta de una base de datos de revistas y libros editados por Elsevier, considerado el mayor proveedor mundial de información científica, técnica y médica. Publica más de 2,000 revistas, así como libros y bases de datos secundarias. Entre las principales editoriales se encuentran: Academic Press, North Holland o Pergamon, entre otras. La colección contiene más de 9.5 millones de documentos en texto completo, de alta calidad científica en 2,500 revistas y más de 11,000 libros, que abarcan diferentes áreas temáticas, entre las cuales se destacan: medicina, biología, física, matemáticas, ingeniería civil, ingeniería química, ingeniería informática, medio ambiente, ciencia de los materiales, ciencias sociales, sociología, artes y humanidades, economía, agricultura. La base de datos anualmente incluye casi 0.5 millones de nuevos documentos. Comprende millones de artículos en una gran cantidad de archivos de información histórica antes de 1995.' where nombre_recurso='ScienceDirect';


update tc_guia_recursos set descripcion='Scopus es una base de datos especializada en información científica, técnica, ciencias médicas y sociales, incluyendo las artes y las humanidades. Scopus abarca 29 millones de resúmenes de más de 18,500 revistas científicas (incluidas las 1,800 revistas de acceso abierto), 425 publicaciones comerciales, 325 series de libros, 250 actas de congresos, 46 millones de registros. Los datos bibliográficos proporcionan información sobre los puntos clave de la base, tales como: identificador de autor; citation Tracker para un mejor control y seguimiento de citas en tiempo real; alertas, RSS feeds y HTML para mantenerse al día, presenta interoperabilidad con SciVerse ScienceDirect, Reaxis y ProQuest CSA Illumina; y permite exportar los datos obtenidos a través de: RefWorks, EndNote y BibTeX. Scopus es una herramienta que ofrece a los investigadores un recurso rápido, sencillo y completo para apoyar sus necesidades de investigación en cualquier ámbito.' where nombre_recurso='Scopus';

update tc_guia_recursos set descripcion='Springer Materials es una base de datos referencial y la más grande y completa plataforma de investigación dedicada a la información sobre materiales, sus propiedades y usos. Incluye todos los volúmenes de la colección “Landolt-Bornstein New Series”, cuyo valor es contar con la mayor y más completa compilación de datos en física y química. También abarca los archivos “Linus Pauling” y las bases de datos “Dortmund of Software and Separation Technology”, Adsorption” , “A Polymer Thermodinamics”.' where nombre_recurso='Springer Materials';
update tc_guia_recursos set descripcion='Springer Protocols es la base de datos más competa de protocolos de laboratorios en ciencias de la vida y biomédicas; compila los métodos de los protocolos y ofrece a los investigadores 30 años de confianza y la posibilidad de reproducirlos paso a paso. Los protocolos son escritos por especialistas y revisados por editores distinguidos es áreas específicas' where nombre_recurso='Springer Protocols';




update tc_guia_recursos set descripcion='UpToDate es una base de datos que apoyan la toma de decisiones clínicas basadas en evidencia y esta creado por profesionales. Más de 5,100 autores, editores y revisores médicos reconocidos mundialmente utilizan un riguroso proceso editorial para sintetizar la información médica reciente en recomendaciones confiables y basadas en evidencia que han demostrado mejorar la calidad y la atención del paciente. Cubre todas las áreas temáticas de la medicina: Urgencias, atención primaria, medicina interna, alergia e inmunología, anestesiología, dermatología, geriatría, hematología, nefrología, entre otras.' where nombre_recurso='UpToDate';



update tc_guia_recursos set descripcion='Wiley Online Library. Editorial fundada en 1807. Proporciona acceso a más de 1400 títulos de revistas en formato electrónico desde 1997 a la fecha. Cubre temas como agricultura, arquitectura, arte, química, computación, ciencias de la tierra, derecho, psicología, comportamiento humano, física, enfermería, medicina, etc.' where nombre_recurso='Wiley Online Library';
update tc_guia_recursos set descripcion='Wiley Protocols es una base de datos que contiene más de 25 años de información la cual se actualiza regularmente por especialistas. Proporciona un acceso fácil y rápido a los resúmenes, listas de materiales y vincula los contenidos de Wiley Online Library. Current Protocols cuenta con herramientas, calculadoras, videos y seminarios en línea para ayudar a los investigadores en el laboratorio.' where nombre_recurso='Wiley Protocols';


